sudo: false
language: node_js
node_js:
  - "0.12"
before_install:
  - "npm install --global ember-cli bower"
before_script:
  - "bower install"
  - "bower install ember#~2.1.0"
  - "bower install ember-data#~2.1.0"
